- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-master-branch-jobs
      - openstack-python3-yoga-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - networking-generic-switch-tempest-dlm
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^networking_generic_switch/tests/.*$
              - ^releasenotes/.*$
              - ^(test-|)requirements.txt$
              - ^tools/.*$
              - ^tox.ini$
              - ^setup.cfg$
    gate:
      jobs:
        - networking-generic-switch-tempest-dlm
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^networking_generic_switch/tests/.*$
              - ^releasenotes/.*$
              - ^(test-|)requirements.txt$
              - ^tools/.*$
              - ^tox.ini$
              - ^setup.cfg$
